### ISSUE TITLE
hosted steam lobby name not visible

### ISSUE THREAD

**Issue by GregHilston** [MichaelMacha/SteamMultiplayerPeerExample#1]
Hey @MichaelMacha ,

I have steam running, and i'm logged in. When i create a steam lobby with the name say "foo", I am unable to have a second free refresh the steam lobby, and see that lobby name in the list.

For context, I am able to create and join say an enet lobby locally, and when i set up port forwarding, remotely.

Any idea why this steam lobby cannot be found?

Thanks for your time,
Grehg

CC: @zach-andrews

**Comment by MichaelMacha** [comment]
I may have a suspicion. If you're using the SpaceWars! demo (I think it was 480, if memory isn't failing me), the servers tend to get seriously overwhelmed with the sheer number of lobbies being created. Because of that, it doesn't generally return every single lobby found. I've encountered other issues on the discord quite similar to this.

If I understand your issue, you simply aren't seeing the lobby you created in the list? This is often a side effect of how the test game ID is run. If you've already got a slot purchased for a releasable app, I would suggest attempting it with your app's ID, and see if perhaps you can find it that way.

I hope this helps.

**Comment by GregHilston** [comment]
@MichaelMacha Ah that makes a lot of sense, and was not apparent to my buddy, and myself when we we're looking into this. I modified some starter code to be able to join Steam Lobby's by ID, and that did work.

I'll close this ticket, and chalk up the issue to be not real, and just a lack of understanding how the lobby system worked/displayed.

Thanks for this piece of valuable information!
